config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :users
  resources :events
root to: 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

    belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show


  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

   @event.user_id = current_user.id    

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


def index


end
    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: %i[ show edit update destroy ]



  def index

   @users = User.all    

  end

  def show
    
    @events = @user.events



  end

 

  def edit
  end

  
  def destroy
    @user.destroy
    redirect_to root_path
  end

 private 
def set_user
  @user = User.find(params[:id])
end

def user_params

  params.require(:user).permit(:email, :password)

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<body class= "body-events">


<p id="notice"><%= notice %></p>
 
 <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron img-events">
        <div class="container">
          <h1 class="display-3"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">EVENTS!</font></font></h1>
          <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Cette endroit montre bien les events et la création meme que vous pouvaient faire des events. </p><p  style="vertical-align: inherit;">Il comprend biensure les dates, la durée, le prix ect... . </font><font style="vertical-align: inherit;">Utilisez-le comme point de départ pour créer quelque chose de plus unique.</font></font></p>
        </div>
      </div>


     
          <div class=" d-flex justify-content-center">  
    <% @events.each do |event| %>
     <ul>     
         <h6> Date</h6>
        <%=  event.start_date %>


                 <h6>duration</h6>
            <%= event.duration %>


                 <h6> titre</h6>
               <%= event.title %>  


         <h6> description</h6>
      <%= event.description %>


                 <h6> prix</h6>
             <%= event.price %> 


         <h6> location</h6>


        <%= event.location %>        


       <br>


        <%= link_to 'Show', event,class: "btn btn-info" %>
        <%= link_to 'Edit', edit_event_path(event), class: "btn btn-success"   %>
        <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %>
     </ul>
    <% end %>
          </div>
    


<br>


<%= link_to 'New Event', new_event_path, class: "btn btn-primary"  %>





</body>





          

      

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @event.duration %>
</p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @event.price %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/home/index.html.erb
<body class= "body-acceuil">


<h1 class= "h1-acceuil" > Bienvenue sur le site de création d'events </h1>


</body>

app/views/layouts/_navigation.html.erb
<header>



<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Eventbrite', root_path, class: "navbar-brand" %>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>



  
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">





<%= link_to 'Evenements', events_path, class: "nav-item nav-link" %>



<% if user_signed_in? %>

 <%= link_to "Profil", user_path(current_user), class: "nav-item nav-link" %>


<%= link_to "deconnexion", destroy_user_session_path, method: :delete, class: "nav-item nav-link"%> 

<% else %>
 <%= link_to "connexion",   new_user_session_path, class: "nav-item nav-link" %>

<%= link_to "inscription", new_user_registration_path, class: "nav-item nav-link" %> 

 <% end %>




  </div>
  </div>
</nav>


</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>APPEventbriteHtmlCss</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Ranchers&display=swap" rel="stylesheet">


    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  
      <%= render partial: 'layouts/navigation' %>
      
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Hello <%= @user.email %></h1>

<ul>

<% @events.each do |event| %>

<li>
    <%= link_to event.title, event_path(event) %> 

</li>    

<% end %>

</ul>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>